### ISSUE TITLE
Unable to restart MonetDB container cleanly in Kubernetes

### ISSUE THREAD

**Issue by dharashashi1975** [MonetDB/MonetDB#7639]
### Describe the bug

Facing a strange bug with monetDB docker image while restarting a container.
- Have created a monetDB image with below docker file

```
FROM monetdb/monetdb:Mar2025

RUN usermod -aG root monetdb && \
    chown -R monetdb:root \
    "${HOME}" \
    /var/monetdb5 && \
    chmod -R 2774 \
    "${HOME}" \
    /var/monetdb5 && \
    chmod 774 /usr/local/bin/entrypoint.sh

STOPSIGNAL SIGINT
```

- When starting first time around the monetDB farm and database get created successfully and can be connected to and used
- However upon a pod restart we see the below error and container wont start successfully

```
Starting MonetDB daemon
another monetdbd already running 
```

- Tried by using an initContainer to remove the .merovigian_lock file to see if it helps. This lets the container start successfully, however we see a different error while the application connects to the DB
-

```
2025-05-23 19:43:03 MSG discovery[11]: new neighbour statefulset-monetdb-0 (statefulset-monetdb-0.monetdb-service.297155e0-a176-4389-8b35-04dbb5ae5526.svc.cluster.local)
2025-05-23 19:43:42 ERR control[11]: !monetdbd: an internal error has occurred 'cannot connect: Connection refused'
2025-05-23 19:43:42 MSG merovingian[11]: starting a proxy failed: cannot connect: Connection refused
2025-05-23 19:43:47 ERR merovingian[11]: client error: cannot connect: Connection refused
```

- This is blocking us to proceed further 

### Reproduction steps

This issue can be reproduced with a mounted volume for /var/monetdb5/dbfarm

### MonetDB release

Mar2025

### Executables source

Release packages

### Operating System

Fedora Linux 40 (Container Image)

### Additional context

This issue is only happening when we have the storage for /var/monetdb5/dbfarm being mounted via CephFS 
file system. It seems to be something related to the dbfarm or monetdb database getting locked and something
lingering on the file-system when the pod is terminated. 

If we delete all contents of dbfarm folder and restart the pod, it starts cleanly and is able to create the database as well.

### Full Name:

Shashidhar Lakshminarayana

### Affiliation:

Siemens

**Comment by sstalin** [comment]
Can you please provide additional info on how do you start the container? For example your `docker run` or relevant part of the yaml template.

**Comment by dharashashi1975** [comment]
The container is started with a kubernetes statefulset yaml as below. It defaults to using the /usr/local/bin/entrypoint.sh that is part of the base monetdb/monetdb:Mar2025 image to start the DB
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-monetdb
  namespace: pano-test2
spec:
  selector:
    matchLabels:
      app: statefulset-monetdb  # has to match .spec.template.metadata.labels
  serviceName: "monetdb-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: statefulset-monetdb  # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-cephfs
        image: busybox
        command:
          - sh
          - -c
          - |
            set -ex
            chmod -R g+rws /var/monetdb5/dbfarm
            echo "Written by Init Container" > /var/monetdb5/dbfarm/init.txt
            
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "25m"
            memory: "32Mi"
        volumeMounts:
        - mountPath: /var/monetdb5/dbfarm
          name: volclaim-data-monetdb
      containers:
        - name: monetdb
          image: <private_repository_path>/panomonet:release.0.0.1
          ports:
            - containerPort: 50000
              name: web-monet
          env:
            - name: MDB_DB_ADMIN_PASS_FILE
              value: /var/run/secrets/mdb_admin_pass_file
          resources:
            limits:
              cpu: 1000m
              memory: 1200Mi
            requests:
              cpu: 700m
              memory: 750Mi
          volumeMounts:
            - name: volclaim-data-monetdb
              mountPath: /var/monetdb5/dbfarm
            - name: monet-creds
              mountPath: /var/run/secrets/mdb_admin_pass_file
              subPath: mdb_admin_pass_file
          securityContext:
            runAsUser: 5000
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 5000
      volumes:
        - name: monet-creds
          secret:
            secretName: monet-secret
  volumeClaimTemplates:
    - metadata:
        name: volclaim-data-monetdb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: panoviz-storageclass
        resources:
          requests:
            storage: 4Gi
```
